trigger:
  branches:
   include:
     - main
  paths:
   include:
     - src/*

pool:
 name: 'My Local Agent' 

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub Login'
        repository: 'umerfarooqsyed/my_first_devops_project'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'


- stage: Push
  displayName: Push image to Docker Hub
  jobs:
  - job: Push
    displayName: Push image to Docker Hub
    steps:
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'Docker Hub Login'
        repository: 'umerfarooqsyed/my_first_devops_project'
        command: 'push'
        tags: '$(tag)'

- stage: UpdateManifests
  displayName: Update k8s manifest files
  jobs:
  - job: UpdateManifests
    displayName: Update k8s manifest files
    steps:
    - script: chmod +x scripts/update_k8s_manifests.sh
      displayName: Make manifest script executable
    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/update_k8s_manifests.sh'
